# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GabrielFerrazFontes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'RxCocoa', '6.0.0-rc.2'

  # Pods for GabrielFerrazFontes

  target 'GabrielFerrazFontesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GabrielFerrazFontesUITests' do
    # Pods for testing
  end

end
